### ISSUE TITLE
Use fetch-ponyfill instead of isomorphic-fetch polyfill

### ISSUE THREAD

**Issue by ctavan** [apollographql/apollo-fetch#22]
Following my reasoning in https://github.com/apollographql/apollo-client/pull/2008 I think it would be a good practice if a library like `apollo-fetch` did not modify the global namespace by polyfilling `fetch`.

Is there any particular reason _not_ to use https://github.com/qubyte/fetch-ponyfill instead? If you would accept a ponyfill instead of a polyfill I'd be happy to contribute a PR.

Bundle-size wise there should be no signifcant difference.

**Comment by giautm** [comment]
Link issues i facing on react-native :(

https://github.com/matthew-andrews/isomorphic-fetch/issues/125

**Comment by joarwilk** [comment]
This really needs to be resolved. @ctavan is your PR ready?

**Comment by ctavan** [comment]
@joarwilk as outlined in #30 I believe `apollo-fetch` should not be bundled with a fetch ponyfill but leave that choice up to the user. I have prepared a PR (#30) for an `apollo-fetch-polyfill` package that comes with the `cross-fetch` polyfill. Still awaiting feedback from the maintainers though.

With that change it would be very simply to provide your own fetch-ponyfill when using the regular `apollo-fetch` which would then come without any polyfill.

**Comment by evans** [comment]
#71 uses `cross-fetch`, so this should be resolved
