### ISSUE TITLE
Unable to override Apollo Client's default content-type 'application/json' header

### ISSUE THREAD

**Issue by aleksdao** [apollographql/apollo-fetch#39]
@jbaxleyiii great meeting you at the GraphQL NYC meetup last night! Really enjoyed yours and Sashko's talks on the innovation within the Apollo + GraphQL ecosystem - this schema stitching (local+remote, remote+remote) stuff is wild and exciting.

We chatted briefly yesterday about the issue I was having with overriding the default content-type `application/json` header that is set by Apollo Client. If you have any thoughts on the best way to resolve this, let me know! I'm happy to contribute back a PR to extend the client's flexibility

**Intended outcome:**

Additional context here: https://github.com/Yelp/yelp-fusion/issues/278#issuecomment-322328370

I'm attempting to make a request to the Yelp GraphQL API server by setting a content-type header of `application/graphql` (as suggested by the Yelp GraphQL docs for sending raw GraphQL queries, https://www.yelp.com/developers/graphql/guides/requests)

```
const networkInterface = createNetworkInterface({
  uri: 'https://api.yelp.com/v3/graphql',
});

networkInterface.use([
  {
    applyMiddleware(req, next) {
      if (!req.options.headers) {
        req.options.headers = {}; // Create the header object if needed.
      }

      req.options.headers.authorization = yelpAccessToken ? `Bearer ${yelpAccessToken}` : null;
      req.options.headers['content-type'] = 'application/graphql';
      req.options.headers['accept-language'] = 'en_US';
      next();
    },
  },
]);

const client = new ApolloClient({
  networkInterface,
});
```
query
```
const RestaurantListingQuery = gql`
  query {
    business(id: "garaje-san-francisco") {
      name
      id
      location {
        city
      }
    }
  }
`;
```

Expected Result: response from Yelp GraphQL API with valid restaurant data
```
{
    "data": {
        "business": {
            "name": "Garaje",
            "id": "garaje-san-francisco",
            "rating": 4.5,
            "url": "https://www.yelp.com/biz/garaje-san-francisco?adjust_creative=x7LWoNv05Hf_vNeFecFImQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_graphql&utm_source=x7LWoNv05Hf_vNeFecFImQ"
        }
    }
}
```

**Actual outcome:**

Instead of overriding the default `content-type: application/json` header, the Apollo client appears to prepend `application/json` to the specified `application/graphql` value. This results in a concatenated `content-type: application/json, application/graphql` header.

<img width="655" alt="screen shot 2017-08-14 at 8 27 57 pm" src="https://user-images.githubusercontent.com/5334479/29297450-1b205b20-812f-11e7-8ce8-7113c17052b9.png">

The result of this request is a malformed `content-type` header, to which the Yelp GraphQL API responds with `Must provide query string.`

**Other observations**

In Postman,
* the Yelp GraphQL API responds with the expected data if `content-type: application/graphql` set
<img width="1119" alt="screen shot 2017-08-12 at 12 28 59 pm" src="https://user-images.githubusercontent.com/5334479/29297561-f38a5448-812f-11e7-8702-8d1a1696782d.png">

* the Yelp GraphQL responds with "Must provide query string" error if `content-type: application/json, application/graphql` set

<img width="1032" alt="screen shot 2017-08-14 at 7 43 09 pm" src="https://user-images.githubusercontent.com/5334479/29297554-e8c36374-812f-11e7-8741-dba7f75e86a7.png">

**Version**
- apollo-client@1.4.0
- react-apollo@1.4.12

**Comment by aleksdao** [comment]
It appears this was just a mistake on my part! If I'm reading this correctly (https://github.com/apollographql/apollo-client/blob/3b5045dfe74183fe060d2027e31317d890755b99/src/transport/networkInterface.ts#L189), the Apollo client calls JSON.stringify on the my query... so I should in fact be sending the default content-type: application/json header in my request.

After removing application/graphql override, this works as expected. Thanks for your help!

**Comment by stubailo** [comment]
Yeah - we've made a somewhat intentional decision to not support the `application/graphql` content type, since it just makes server implementations and other tools more complex by adding another branch in addition to GET and POST with JSON.

However, it would be great to have at least an error printed if you try to set a different header for that - do you think that would have been helpful?

**Comment by aleksdao** [comment]
Hey Sashko - thx for getting back to me. Agree a dev-friendly error message would've been helpful, though I realize I sort of botched the whole setting headers thing.

I set `req.options.headers['content-type'] = 'application/graphql'`. For whatever reason, this gets merged with the default `Content-Type` header to create a `Content-Type: application/json application/graphql` mega-header. 

On the other hand, if I set `req.options.headers['Content-Type'] = application/graphql` (`Content-Type` is capitalized), this overrides the default header as expected, and the Apollo client sends a request with `Content-Type: application/graphql` (I'm aware this wouldn't have worked anyways)

**Comment by ocdkube** [comment]
Hi there,
I am setting content-type of request to  'application/keyauth.api.v1' but when checking in browser, getting that it is sending as 'application/json'

const restLink = new RestLink({
  uri: process.env.REACT_APP_API_SERVER + process.env.REACT_APP_API_SERVER_VERSION,
  credentials: 'omit',
})

const authRestLink = new ApolloLink((operation, forward) => {
  operation.setContext(async ({headers}) => {
    const token = await localStorage.getItem("token");
    return {
      headers: {
        ...headers,
        Accept: "application/json",
        'Content-Type': 'application/keyauth.api.v1',
        Authorization: localStorage.getItem('token') ? 'Bearer ' + localStorage.getItem('token') : ""
      }
    };
  });
  return forward(operation);
});

const link = ApolloLink.from([
  authRestLink,
  restLink,
]);

const cache = new InMemoryCache()
const client = new ApolloClient({
  link,
  cache,
})
![gitissue](https://user-images.githubusercontent.com/40567908/49151487-0e63b880-f336-11e8-9904-d31a5788006a.png)
