### ISSUE TITLE
Support HTTP_PROXY

### ISSUE THREAD

**Issue by gajus** [apollographql/apollo-fetch#4]
Support of HTTP proxy (on backend services) is a critical component of a HTTP client.

It is a simple abstraction to implement using `http(s)-proxy-agent` libraries, https://github.com/gajus/xfetch/blob/fe4b5a6c258fedc6d28f873368d7e06ea625b6bc/src/index.js#L99-L109.

**Comment by stubailo** [comment]
Is there any way to get this support with the standard `fetch` API?

If not, is passing in a custom `fetch` function a good solution for you?

**Comment by gajus** [comment]
> Is there any way to get this support with the standard fetch API?

No.

> If not, is passing in a custom fetch function a good solution for you?

Yes.

**Comment by stubailo** [comment]
@gajus is there anything you need beyond the current ability to pass in a custom fetch function to integrate your xfetch library?

**Comment by stubailo** [comment]
If that is a good solution, it would be great to add some documentation about how to use that!

**Comment by gajus** [comment]
> @gajus is there anything you need beyond the current ability to pass in a custom fetch function to integrate your xfetch library?

Just added it to my project – it works great.

> If that is a good solution, it would be great to add some documentation about how to use that!

Do you need help with an example showing how to setup HTTP_PROXY with `node-fetch`?

**Comment by stubailo** [comment]
@gajus yeah a PR to add an example about that in the README would be awesome!

**Comment by evanshauser** [comment]
@gajus I'm going to close this issue, since it seems we've come to a solution with passing a custom solution. It would be incredible if you add an example into the `docs` folder for using HTTP_PROXY! Please let me know if you want any support.

**Comment by gajus** [comment]
Sorry guys, I am completely overloaded the past 2 months. I have this one on personal Trello board.
