### ISSUE TITLE
Can custom fetch be the default behavior

### ISSUE THREAD

**Issue by rtorr** [apollographql/apollo-fetch#5]
Howdy! Long time user of the apollo graphql tools. This library hits a lot of good notes, and was able to use it instead of a home grown solution, due to the API being small and plugable.

Would it be possible to not include isomorphic-fetch by default, and have that be the custom option?

I am using a different fetch implementation, and I would like to not include isomorphic-fetch at all if possible.

Default behavior would be to use native browser fetch. If a custom fetch is needed (which would be yes in my case), then you still have the customFetch property. For users who need isomorphic fetch, they could also use the customFetch property.

**Comment by stubailo** [comment]
My main concern here is that people will often write their code, test it on chrome, then ship it; their app ends up not working because some browsers don't include fetch (notably Safari) and then it feels like the library is broken.

Is there any way we can serve both cases?

**Comment by rtorr** [comment]
I am currently using unfetch, but I guess it is all preference. Feel free to close if you disagree, I see value in your point. Just feels weird to include multiple versions of fetch, when one can be overwritten.

**Comment by stubailo** [comment]
> Just feels weird to include multiple versions of fetch, when one can be overwritten.

Yeah, that's a good point for sure. It's a bummer that it's so hard to make npm packages conditionally include code. On the other hand, `fetch` is only like a 2kb polyfill as far as I know?

Maybe there's something we can do to satisfy both needs.

**Comment by rtorr** [comment]
Yep, maybe I could switch to isomorphic. Thanks for reading, and making cool shit ;)
