### ISSUE TITLE
Websocket support?

### ISSUE THREAD

**Issue by zackify** [apollographql/apollo-fetch#50]
Sorry if this is the wrong place to ask this. Will this library ever handle requests over websockets? This has supported full websocket transport for a couple months: https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport but I haven't found a way to use graphiql that way or anyone really supporting full websocket transport.

**Comment by stubailo** [comment]
I think you can definitely use GraphiQL with that! Probably best to open an issue there, since apollo-fetch is specifically for HTTP.
