### ISSUE TITLE
Apollo Client 2.0 usage

### ISSUE THREAD

**Issue by pho3nixf1re** [apollographql/apollo-fetch#80]
Apollo Client 2.0 requires a `link` option which is in conflict with setting the uri on `createApolloFetch`. Does this imply that `apollo-fetch` is now legacy for use with pre 2.0 clients?

**Comment by ctavan** [comment]
@pho3nixf1re you are right, with Apollo Client 2.0 you no longer use `apollo-fetch` but `apollo-link` instead. See https://www.apollographql.com/docs/react/2.0-migration.html for an example.

See also https://github.com/apollographql/apollo-fetch/pull/30#issuecomment-349463447

**Comment by pho3nixf1re** [comment]
@ctavan do you want to change this issue into a README fix to add a note? Otherwise you may get more questions like this.

**Comment by ctavan** [comment]
@pho3nixf1re well, I'm not a maintainer of `apollo-fetch`, so I don't feel entitled to decide how `apollo-fetch` should be communicated. If it is decided to deprecate `apollo-fetch` entirely, then this should definitely be noted in the README.

@evans @jbaxleyiii how do you think about this?

**Comment by evans** [comment]
We don't have a concrete plan for `apollo-fetch`. I think there is a reasonable argument for keeping it around as a lightweight client, separate from Apollo Client.

When we start to work on continuous deployment and other monorepo tooling, `apollo-fetch` might become a testing ground for that development.

@ctavan is there anything more you would like to see `apollo-fetch` do?

**Comment by ctavan** [comment]
@evans no, just as you mention I would also like to keep `apollo-fetch` as an ultra-lightweight client. All I would really need is a variant of it that does not pollute the globale scope with a `fetch` polyfill, but that should be achieved by #30.

**Comment by evans** [comment]
@ctavan It seems like the best way to go with `apollo-fetch` is make you a [collaborator](https://github.com/apollographql/apollo-fetch/invitations)! 🎉 

I can also give you publish permissions if you would like to keep `apollo-fetch` alive as an ultra-lightweight client for the long term

**Comment by ctavan** [comment]
I have added a deprecation warning to the README with #193 for now.

**Comment by kachkaev** [comment]
Given that this module is deprecated, what's the best way to fetch graphql data inside an express server (say, in a background job)?
